### ISSUE TITLE
Token creation fails on MetaMask

### ISSUE THREAD

**Issue by fhildeb** [lukso-network/example-dapp-lsps#25]
<img width="1790" alt="Bildschirmfoto 2022-06-16 um 16 45 34" src="https://user-images.githubusercontent.com/61689369/174096430-8c75763f-8ae8-4cd9-933d-7695b44fe41b.png">

Error after last (3rd) transaction.

**Comment by Hugoo** [comment]
Nice thks- it is because the app thinks a UP SC has been injected so it tries to update the erc725y values - instead we should try catch and display a correct msg.
