### ISSUE TITLE
Send token popup does not show ProfileComponent of receiver

### ISSUE THREAD

**Issue by fhildeb** [lukso-network/example-dapp-lsps#28]
<img width="958" alt="Bildschirmfoto 2022-06-16 um 23 20 30" src="https://user-images.githubusercontent.com/61689369/174167205-d1cfa8f5-e4ef-4b75-86aa-73218313879c.png">

**Comment by Hugoo** [comment]
Re use `ProfileComponent.vue` here - only call it when the address set is valid (v-if=isValidAddress(address))
