### ISSUE TITLE
ProfileComponent does not show profile picture

### ISSUE THREAD

**Issue by fhildeb** [lukso-network/example-dapp-lsps#29]
<img width="1790" alt="Bildschirmfoto 2022-06-16 um 23 21 57" src="https://user-images.githubusercontent.com/61689369/174167705-3e53c81d-ef98-4b2d-9477-af1e871583ad.png">

Might be an edge case, but nothing is showing for me:

Address: `0x0Ac71c67Fa5E4c9d4af4f99d7Ad6132936C2d6A3`
Profile Explorer: [universalprofile.cloud/0x0Ac71c67Fa5E4c9d4af4f99d7Ad6132936C2d6A3](https://universalprofile.cloud/0x0Ac71c67Fa5E4c9d4af4f99d7Ad6132936C2d6A3)

**Comment by olusoladavid** [comment]
@fhildeb I will investigate this issue. Thanks for submitting
