### ISSUE TITLE
Add feature to send LSP8 NFTs

### ISSUE THREAD

**Issue by Hugoo** [lukso-network/example-dapp-lsps#32]
The current implementation does not allow user to send LSP8 token - it fails on send:

![image](https://user-images.githubusercontent.com/477945/174270778-5fd5784b-69b7-4cf0-9a73-a6a7c0acfd28.png)

The current page has been made for sending LSP7 tokens - not LSP8.

The send component should support sending LSP8 - by using the LSP8 contract abi.

**Comment by CallumGrindle** [comment]
Owned LSP8 NFT tokenIds should appear in the portfolio section. Clicking on it brings up a modal to send that specific NFT tokenId

Owned NFTs should have a rectangular boarder, owned LSP7 tokens should have a rounded boarder

**Comment by CallumGrindle** [comment]
Each token mint should add LSP4 metadata to the that tokenId.
