### ISSUE TITLE
LSP8 Asset Collection sometimes shows out of funds

### ISSUE THREAD

**Issue by fhildeb** [lukso-network/example-dapp-lsps#41]
<img width="1790" alt="Bildschirmfoto 2022-06-17 um 19 17 16" src="https://user-images.githubusercontent.com/61689369/174347208-010d98c4-6d10-41e3-afc1-3a8ac5e06ffb.png">

even if the wallet has enough funds

**Comment by CallumGrindle** [comment]
I suggest we keep an eye on this and see if the behaviour continues. I suspect it is not related to this page as the gas balance calc is handled by the browser extension (unless the gas estimate is wrong within the page)

**Comment by CallumGrindle** [comment]
Saw this same error just now. Weird. Will keep an eye out...

**Comment by CallumGrindle** [comment]
This was caused by relayer consumers having low LYX balance. Have topped up the accounts so this should be fixed. Closing
