### ISSUE TITLE
LSP8 Collection: Transaction progress

### ISSUE THREAD

**Issue by fhildeb** [lukso-network/example-dapp-lsps#42]
<img width="1790" alt="Bildschirmfoto 2022-06-17 um 19 22 26" src="https://user-images.githubusercontent.com/61689369/174348258-9aa9fb19-04c4-404e-97ed-5d3f004d7ad9.png">

- Creating an Token collection shows token properties/input fields again after 3rd transaction, which should not be the case
- after all the transactions went trough, there should be an "success" text like on TokenCreation

**Comment by CallumGrindle** [comment]
Saw this same error just now. Weird. Will keep an eye out...

**Comment by fhildeb** [comment]
closed on #44
