### ISSUE TITLE
Improve LSP8 minting

### ISSUE THREAD

**Issue by CallumGrindle** [lukso-network/example-dapp-lsps#47]
When minting LSP8 NFTs Each token mint should add LSP4 metadata to that tokenId.

```
{
  "name": "LSP8MetadataJSON:<address|uint256|bytes32>",
  "key": "0x9a26b4060ae7f7d5e3cd0000<address|uint256|bytes32>",
  "keyType": "Mapping",
  "valueType": "bytes",
  "valueContent": "JSONURL"
}
```

LSP4Metadata should use name, description and icon

When minting, set the tokenId as `web3.utils.padRight(web3.utils.stringToHex('My NFT Item ID'), 64)` using the Token ID field
The token ID text should not be longer than 30 characters, so make a max size attribute on the inout field

**Comment by Hugoo** [comment]
The LSP8 minting is already done - or is it to add more features?

**Comment by Hugoo** [comment]
Ah ok i got it !
Nice ! 👍
