### ISSUE TITLE
Outsource all styling into styles.less

### ISSUE THREAD

**Issue by fhildeb** [lukso-network/example-dapp-lsps#69]
All styles should be in one single place

**Comment by dzbo** [comment]
@fhildeb If I'm not mistaken all styles are already in one https://github.com/lukso-network/example-dapp-lsps/blob/main/src/styles.less file, correct?

**Comment by CallumGrindle** [comment]
Closing as CSS is already in one file. @fhildeb if you meant something else can you clarify?
