### ISSUE TITLE
Token stays in portfolio if you send full supply

### ISSUE THREAD

**Issue by fhildeb** [lukso-network/example-dapp-lsps#82]
If you send away the full supply of a token, it should be removed from localStorage array and portfolio should remove the asset without having to refresh the page/dApp.

**Comment by fhildeb** [comment]
- [ ] MM: update localStorage
- [ ] UPE reload assets (or remove manually?!)

**Comment by CallumGrindle** [comment]
Assets are now removed from portfolio when sending full supply when using UP extension. 
Still needs to be implemented for MM local storage
